### ISSUE TITLE
Add the Github webhook to the ideascube repo

### ISSUE THREAD

**Issue by bochecha** [ideascube/ci-conf#1]
This is needed to have packages built automatically for each new tag.

**Comment by yohanboniface** [comment]
Do you have the webhook details by hand?

**Comment by bochecha** [comment]
Yes, sorry I should have given them right away:
- payload URL: http://buildbot.ideascube.org/change_hook/github
- content type: `application/json` (the default)
- secret: choose something very secret, anything, and then we need to put that in the buildbot configuration

Finally, select the « Let me select individual events » option, and select only the « create » event.

That should be it.

**Comment by bochecha** [comment]
Note that we'll need to change the payload URL when we move to ideascube.org ( #3 )

**Comment by bochecha** [comment]
And we already moved to ideascube.org, so we can directly set the permanent payload URL.

**Comment by yohanboniface** [comment]
Done :)
