### ISSUE TITLE
IRC notices

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ci-conf#7]
Could be nice to have an IRC notice on #ideascube when:
- a build starts
- a build ends

With details about version and architecture.

**Comment by yohanboniface** [comment]
Ref: http://docs.buildbot.net/0.8.1/IRC-Bot.html

**Comment by bochecha** [comment]
This should now be done in production, let's wait until the next build to check that it works, and then I'll document how it's set up.

**Comment by bochecha** [comment]
Confirming it works. :)

So I just need to document it, now.

**Comment by yohanboniface** [comment]
I've seen the notice for the start, but none for the success (armh) nor the failure (adm), is that expected?

**Comment by bochecha** [comment]
I've seen builds starting:

```
<ideascubebot> build #53 of build-amd64-pkg started (including [0.10.3])
```

And builds succeeding:

```
<ideascubebot> build #46 of build-armhf-pkg is complete: Success [build successful]  Build details are at http://buildbot.ideascube.org/builders/build-armhf-pkg/builds/46
...
<ideascubebot> build #53 of build-amd64-pkg is complete: Success [build successful]  Build details are at http://buildbot.ideascube.org/builders/build-amd64-pkg/builds/53
```

But you're right, I haven't seen any build failures...

I'll have a look soon.
